format = """$directory$git_branch$python$conda
($shell)$username$character"""
right_format = "$status$cmd_duration"

[directory]
fish_style_pwd_dir_length = 1

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = "🌱 "

[shell]
bash_indicator = "Ｂ"
zsh_indicator = "Ｚ"
powershell_indicator = "PS"
style = "purple bold"
disabled = false

[python]
format = '[PY\(${pyenv_prefix}\):(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = 'env'

[conda]
symbol = 'C:'
format = '[$symbol$environment]($style) '

[username]
format = "[U:$user]($style) "

[status]
disabled = false

[cmd_duration]
min_time = 1_000
format = "[$duration]($style) "
style = "white"
show_notifications = true
min_time_to_notify = 30_000
